commerce_order.commerce_order_item_type.*.third_party.commerce_claim_gift_aid:
  type: mapping
  label: 'Commerce gift aid order item type'
  mapping:
    gift_aid:
      type: string
      label: 'Is eligible for gift aid'
